// rtc-mode/clients/web/vue/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import Configuration from './views/Configuration.vue'
import Room from './views/Room.vue'
import './App.css'

/** Which language the conversation runs in. */
export type Lang = 'en' | 'zh'

export interface AppConfig {
  language: Lang
  avatarId: string
}

const config = ref<AppConfig | null>(null)

function handleReady(c: AppConfig) {
  config.value = c
}
</script>

<template>
  <div class="app">
    <div :class="['view', { active: !config }]">
      <Configuration @ready="handleReady" />
    </div>
    <div :class="['view', { active: !!config }]">
      <Room v-if="config" :config="config" />
    </div>
  </div>
</template>

// agora-demo/clients/web/nextjs-iframe/iframe-content/src/App.tsx
import { useState, useCallback } from 'react'
import Configuration from './views/Configuration'
import Room from './views/Room'
import './App.css'

/** Which language the conversation runs in. */
export type Lang = 'en' | 'zh'

export interface AppConfig {
  language: Lang
  avatarId: string
}

export default function App() {
  const [config, setConfig] = useState<AppConfig | null>(null)

  const handleReady = useCallback((c: AppConfig) => setConfig(c), [])

  return (
    <div className="app">
      <div className={`view ${config ? '' : 'active'}`}>
        <Configuration onReady={handleReady} />
      </div>
      <div className={`view ${config ? 'active' : ''}`}>
        {config && <Room config={config} />}
      </div>
    </div>
  )
}
